eve_auth/urls.py
from django.urls import path

import eve_auth.views


app_name = 'eve_auth'


urlpatterns = [
    path('add/character/', eve_auth.views.StandardLogin.as_view(), name='login'),
    path('add/scraper/', eve_auth.views.ScraperLogin.as_view(), name='login_scraper'),
    path('callback/', eve_auth.views.CallbackView.as_view(), name='callback'),
]

freight/urls.py
from django.urls import path
from django.views.generic.base import RedirectView

import freight.views


app_name = 'freight'


urlpatterns = [
    path('', freight.views.ContractListView.as_view(), name='contract_list'),
    path('calculator/', freight.views.CalculatorView.as_view(), name='calculator'),
    path('calc/', RedirectView.as_view(url='/calculator/', permanent=True)),
    path('leaderboard/', freight.views.LeaderboardView.as_view(), name='leaderboard'),
    path('view/<int:cid>/', freight.views.IngameContractView.as_view(), name='ingame_contract'),
]

freight/models.py
from django.db import models, transaction

from eve_esi import ESI


class EntityManager(models.Manager):
    def bulk_resolve(self, ids):
        if len(ids) == 0:
            return

        data = ESI.get_client().request(
            # HACK: Max items for this endpoint is 1000
            # You should really loop over the items in groups of 1000
            # But this way we'll catch 1000 new entities every time the task
            # runs and it will eventually complete.
            ESI['post_universe_names'](ids=list(ids)[:1000])
        ).data

        with transaction.atomic():
            for entity in data:
                Entity.objects.update_or_create(
                    id=entity['id'],
                    defaults={
                        'name': entity['name'],
                        'type': Entity.TYPE_MAP[entity['category']]
                    }
                )


class Entity(models.Model):
    TYPE_CHARACTER = 0
    TYPE_CORPORATION = 1
    TYPE_ALLIANCE = 2

    TYPE_CHOICES = (
        (TYPE_CHARACTER, 'Character'),
        (TYPE_CORPORATION, 'Corporation'),
        (TYPE_ALLIANCE, 'Alliance'),
    )

    TYPE_MAP = {
        'character': TYPE_CHARACTER,
        'corporation': TYPE_CORPORATION,
        'alliance': TYPE_ALLIANCE
    }

    id = models.BigIntegerField(primary_key=True)
    name = models.CharField(max_length=64, db_index=True, unique=True)
    type = models.SmallIntegerField(choices=TYPE_CHOICES)

    objects = EntityManager()

    def __str__(self):
        return self.name


class Location(models.Model):
    id = models.BigIntegerField(primary_key=True)
    full_name = models.CharField(max_length=64)
    short_name = models.CharField(max_length=64)

    def __str__(self):
        return self.short_name


class Contract(models.Model):
    STATUS_OUTSTANDING = 0
    STATUS_IN_PROGRESS = 1
    STATUS_FINISHED_ISSUER = 2
    STATUS_FINISHED_CONTRACTOR = 3
    STATUS_FINISHED = 4
    STATUS_CANCELLED = 5
    STATUS_REJECTED = 6
    STATUS_FAILED = 7
    STATUS_DELETED = 8
    STATUS_REVERSED = 9
    STATUS_DISAPPEARED = 10

    STATUS_CHOICES = (
        (STATUS_OUTSTANDING, 'Outstanding'),
        (STATUS_IN_PROGRESS, 'In progress'),
        (STATUS_FINISHED_ISSUER, 'Finished (issuer)'),
        (STATUS_FINISHED_CONTRACTOR, 'Finished (contractor)'),
        (STATUS_FINISHED, 'Finished'),
        (STATUS_CANCELLED, 'Canceled'),
        (STATUS_REJECTED, 'Rejected'),
        (STATUS_FAILED, 'Failed'),
        (STATUS_DELETED, 'Deleted'),
        (STATUS_REVERSED, 'Reversed'),
        (STATUS_DISAPPEARED , 'Disappeared'),
    )

    # TODO: Hey do you smell any technical debt here?

    STATUS_MAP = {
        'outstanding': 0,
        'in_progress': 1,
        'finished_issuer': 2,
        'finished_contractor': 3,
        'finished': 4,
        'cancelled': 5,
        'rejected': 6,
        'failed': 7,
        'deleted': 8,
        'reversed': 9

    }

    id = models.BigIntegerField(primary_key=True)
    title = models.CharField(max_length=256)
    volume = models.DecimalField(max_digits=32, decimal_places=5)
    status = models.SmallIntegerField(db_index=True, choices=STATUS_CHOICES)

    issuer = models.ForeignKey(
        Entity,
        models.CASCADE,
        related_name='issued_contracts'
    )
    acceptor = models.ForeignKey(
        Entity,
        models.CASCADE,
        related_name='accepted_contracts',
        null=True
    )

    collateral = models.DecimalField(max_digits=32, decimal_places=2)
    reward = models.DecimalField(max_digits=32, decimal_places=2)

    date_accepted = models.DateTimeField(null=True)
    date_completed = models.DateTimeField(null=True)
    date_expired = models.DateTimeField()
    date_issued = models.DateTimeField()

    days_to_complete = models.SmallIntegerField()

    start_location = models.ForeignKey(
        Location,
        models.CASCADE,
        related_name='start_contracts',
        db_constraint=False
    )
    end_location = models.ForeignKey(
        Location,
        models.CASCADE,
        related_name='end_contracts',
        db_constraint=False
    )

    @property
    def start(self):
        try:
            return self.start_location
        except Location.DoesNotExist:
            return None

    @property
    def end(self):
        try:
            return self.end_location
        except Location.DoesNotExist:
            return None

    def __str__(self):
        return "{org} to {dst} ({volume} m3)".format(
            org=self.start.short_name if self.start is not None else 'Unknown',
            dst=self.end.short_name if self.end is not None else 'Unknown',
            volume=self.volume
        )


class Route(models.Model):
    start = models.ForeignKey(
        Location,
        models.CASCADE,
        related_name='+',
        db_index=True
    )
    end = models.ForeignKey(
        Location,
        models.CASCADE,
        related_name='+',
        db_index=True
    )

    price_per_m3 = models.IntegerField()

    def __str__(self):
        return "{org} to {dst}".format(
            org=self.start.short_name,
            dst=self.end.short_name
        )

freight/views.py
import datetime

from django.shortcuts import render
from django.views.generic.base import View, TemplateView
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse
from django.db.models import Count, Sum, Avg, Q, F, Subquery, OuterRef, ExpressionWrapper, fields
from django.db.models.functions import Coalesce, Greatest
from django.conf import settings

from freight.models import Route, Contract, Entity


class ContractListView(TemplateView):
    template_name = 'freight/contract_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['contracts'] = (
            Contract.objects
            .filter(
                status=Contract.STATUS_OUTSTANDING,
                date_expired__gt=datetime.datetime.now()
            )
            .annotate(route_price_per_m3=Coalesce(
                Subquery(
                    Route.objects.filter(
                        start=OuterRef('start_location'),
                        end=OuterRef('end_location')
                    ).values('price_per_m3')
                ),
                -1
            ))
            .annotate(suggested_reward=(
                Greatest(
                    5000000.0,
                    F('route_price_per_m3') * F('volume') + F('collateral') * 0.01,
                    output_field=fields.FloatField()
                )
            ))
        )
        return context


class CalculatorView(TemplateView):
    template_name = 'freight/calculator.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['routes'] = Route.objects.order_by('start', 'end')
        context['parameters'] = settings.FREIGHT_PARAMETERS
        return context


class LeaderboardView(View):
    def get(self, request):
        query = (
            Entity.objects
            .filter(accepted_contracts__status=Contract.STATUS_FINISHED)
            .annotate(contracts_completed=Count(
                'accepted_contracts',
            ))
            .filter(contracts_completed__gt=10)
            .annotate(volume_moved=Sum(
                'accepted_contracts__volume',
            ))
            # .annotate(average_ttc=Avg(
            #     Subquery(
            #         Contract.objects
            #         .filter(
            #             status=Contract.STATUS_FINISHED,
            #             acceptor=OuterRef('id')
            #         )
            #         .annotate(
            #             ttc=ExpressionWrapper(
            #                 F('date_completed') - F('date_accepted'),
            #                 output_field=fields.DurationField()
            #             )
            #         )
            #         .values('ttc')
            #     ),
            #     output_field=fields.DurationField()
            # ))
        )

        return render(
            request,
            'freight/leaderboard.html',
            context={
                'ranking_completed': query.order_by('-contracts_completed')[:5],
                'ranking_volume': query.order_by('-volume_moved')[:5],
                # 'ranking_ttc': query.order_by('average_ttc')[:5],
            }
        )


@method_decorator(csrf_exempt, name='dispatch')
class IngameContractView(View):
    def post(self, request, cid):
        for char in request.user.character_set.filter(scope_open_window=True):
            char.open_contract(cid)
        return HttpResponse(status=204)

freight/templates/freight/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>TEST Freight</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.1/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.1/css/bootstrap.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.18/css/dataTables.bootstrap4.min.css" />

    <!-- Custom styles for this template -->
    <link href="{% static 'css/freight.css' %}" rel="stylesheet">

  </head>

  <body id="page-top">

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark" id="mainNav">
      <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="{% url 'freight:contract_list' %}"><i class="fas fa-shipping-fast"></i> TEST Freight</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'freight:contract_list' %}">Contracts</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'freight:calculator' %}">Calculator</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'freight:leaderboard' %}">Leaderboard</a>
            </li>
            {% if request.user.is_authenticated %}
            {% comment %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'eve_auth:login' %}">Add character</a>
            </li>
            {% endcomment %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'logout' %}">Log out</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">{{ request.user.username }}</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'eve_auth:login' %}">Log in</a>
            </li>
              {% endif %}
          </ul>
        </div>
      </div>
    </nav>

    {% block content %}{% endblock %}

    <!-- Bootstrap core JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.1/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.18/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.18/js/dataTables.bootstrap4.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/numeral.js/2.0.6/numeral.min.js"></script>

    {% block javascript %}{% endblock %}
  </body>

</html>

freight/templates/freight/calculator.html
{% extends "freight/base.html" %}
{% load humanize %}

{% block content %}
<header class="bg-primary text-white">
    <div class="container text-center">
    <h1>Reward Calculator</h1>
    <p class="lead">Cheapest rates in all of New Eden guaranteed*</p>
    </div>
</header>


<section id="about">
    <div class="container">
        <div class="alert alert-danger">
          <strong>Danger!</strong> Do not include containers of any kind in your contract!
        </div>

        <div class="row" style="margin:10px;">
        <div class="col-sm-2">Route:</div>
        <div class="col-sm-6">

        <select name="route" id="route" class="form-control">
            {% for r in routes %}
            <option value="{{ r.price_per_m3 }}">{{ r.start.short_name }} &rightarrow; {{ r.end.short_name }} ({{ r.price_per_m3 }} ISK/m&sup3;)</option>
            {% endfor %}
        </select>
        </div>
        </div>

        <div class="row" style="margin:10px;">
        <div class="col-sm-2">Contract Size:</div>
        <div class="col-sm-6">
            <div class="input-group add-on">
                <input type="text" id="m3" class="form-control" value="0" />
                <div class="input-group-append">
                    <div class="input-group-text">m³</div>
                </div>
            </div>
        </div>
        <div class="col-sm-4">({{ parameters.max_size|intword }} max | {{ parameters.recommended_size|intword}} recommended)</div>
        </div>

        <div class="row" style="margin:10px;">
        <div class="col-sm-2">Collateral:</div>
        <div class="col-sm-6">
            <div class="input-group add-on">
                <input type="text" id="collat" class="form-control" value="0" />
                <div class="input-group-append">
                    <div class="input-group-text">ISK</div>
                </div>
            </div>
        </div>
        <div class="col-sm-4">(Less than {{ parameters.recommended_collateral|intword }} recommended)</div>
        </div>

        <dl>
            <dt>Reward</dt>
            <dd id="reward">0 ISK</dd>
            <dt>Recommendations</dt>
            <dd id="recomendation"></dd>
        </dl>
    </div>
</section>
{% endblock %}

{% block javascript %}
<script>
const clean_regex = /^\d+(?:\.\d+)?\s*$/i;
const thousand_regex = /^\d+(?:\.\d+)?\s*k$/i;
const million_regex = /^\d+(?:\.\d+)?\s*m(?:illion)?$/i;
const billion_regex = /^\d+(?:\.\d+)?\s*b(?:illion)?$/i;

function collateral() {
    var collateralRate = {{ parameters.collateral_rate }};
    var maxSize = {{ parameters.max_size }};
    var recomendedCollateral = {{ parameters.recommended_collateral }};
    var recomendedSize = {{ parameters.recommended_size }};
    var minPrice = {{ parameters.min_price }};

    var m3Rate = parseInt($("#route").val());

    var size;
    var size_text = $("#m3").val();

    if (size_text.match(billion_regex) != null) {
        size = 1000000000 * parseFloat(size_text);
    } else if (size_text.match(million_regex) != null) {
        size = 1000000 * parseFloat(size_text);
    } else if (size_text.match(thousand_regex) != null) {
        size = 1000 * parseFloat(size_text);
    } else if (size_text.match(clean_regex) != null) {
        size = parseFloat(size_text);
    } else {
        size = NaN;
    }

    var collateral;
    var collateral_text = $("#collat").val();

    if (collateral_text.match(billion_regex) != null) {
        collateral = 1000000000 * parseFloat(collateral_text);
    } else if (collateral_text.match(million_regex) != null) {
        collateral = 1000000 * parseFloat(collateral_text);
    } else if (collateral_text.match(thousand_regex) != null) {
        collateral = 1000 * parseFloat(collateral_text);
    } else if (collateral_text.match(clean_regex) != null) {
        collateral = parseFloat(collateral_text);
    } else {
        collateral = NaN;
    }

    var reward = Math.max(minPrice, (m3Rate * size) + (collateral * collateralRate));

    $("#reward").text(reward.toFixed(2).toString() + " (" + (reward.toFixed(2)/1000000).toFixed(2) + " Million ISK)");

    if (size > maxSize) {
        $("#recomendation").text("The fuck are you trying to move? A titan? Split your contract nerd");
    } else if (reward > minPrice) {
        $("#recomendation").text("None, go for it!");
    } else {
        $("#recomendation").text("Come on now, ain't nobody got time to move your shit for less than 5 million ISK");
    }

    if (size > recomendedSize || collateral > recomendedCollateral){
        $("#recomendation").text("Consider splitting your contract into smaller chunks for faster service.");
    }

    if (isNaN(collateral) || isNaN(size)){
        $("#reward").text("");
        $("#recomendation").text("Please try filling in all the fields correctly, it's the least you can do after all");
    }
}

$("#route").on("input", null, null, collateral);
$("#m3").on("input", null, null, collateral);
$("#collat").on("input", null, null, collateral);

collateral();
</script>
{% endblock %}

freight/templates/freight/contract_list.html
{% extends "freight/base.html" %}
{% load humanize %}
{% load short_natural_time %}
{% load reward_percentage %}

{% block content %}
<header class="bg-primary text-white">
    <div class="container text-center">
    <h1>Contract List</h1>
    <p class="lead">Looking to create a contract? Try the <a href="{% url 'freight:calculator' %}">calculator</a>!</p>
    </div>
</header>

<section id="about">
    <div class="container">
    <table id="contracts" style="width: 100%;">
    <thead>
        <tr>
            <th>Pickup</th>
            <th>Dropoff</th>
            <th>Volume</th>
            <th>Suggested</th>
            <th>Reward</th>
            <th>Collateral</th>
            <th>TTC</th>
            <th>Expires</th>
            <th data-visible="false">Client</th>
            <th>Open</th>
        </tr>
    </thead>
    <tbody>
        {% for c in contracts %}
        <tr class="">
            <td>{{ c.start.short_name|default:"Unknown" }}</td>
            <td>{{ c.end.short_name|default:"Unknown" }}</td>
            <td data-sort="{{ c.volume }}">{{ c.volume|floatformat:2 }} m&sup3;</td>
            {% if c.route_price_per_m3 >= 0 %}
            <td data-sort="{{ c.suggested_reward }}">{{ c.suggested_reward|intword }}</td>
            {% else %}
            <td data-sort="-1">&ndash;</td>
            {% endif %}
            <td data-sort="{{ c.reward }}">{{ c.reward|intword }}
                {% if c.route_price_per_m3 >= 0 %}
                    {% if c.reward >= c.suggested_reward %}
                    (<span class="text-success">{% reward_difference c.reward c.suggested_reward %}%</span>)
                    {% elif c.reward < c.suggested_reward %}
                    (<span class="text-danger">{% reward_difference c.reward c.suggested_reward %}%</span>)
                    {% endif %}
                {% endif %}
            </td>
            <td data-sort="{{ c.collateral }}">{{ c.collateral|intword }}</td>
            <td>{{ c.days_to_complete }}</td>
            <td data-sort="{{ c.date_expired|date:'c' }}">{{ c.date_expired|short_natural_time }}</td>
            <td>{{ c.issuer.name }}</td>
            <td><button type="button" class="btn btn-primary btn-sm" onclick="view_contract({{ c.id }});" {% if not request.user.is_authenticated %}disabled{% endif %}>In-game</button></td>
        </tr>
        {% endfor %}
    </tbody>
    </table>
    </div>
</section>
{% endblock %}

{% block javascript %}
<script>
$(document).ready( function () {
    $('#contracts').DataTable({
        "pageLength": 100,
        "order": [[ 7, "asc" ]]
    });
} );

function view_contract(cid) {
    // HACK: Wow this is disgusting.
    $.post("{% url 'freight:ingame_contract' 111111111 %}".replace("111111111", cid));
}
</script>
{% endblock %}

freight/templates/freight/leaderboard.html
{% extends "freight/base.html" %}
{% load humanize %}

{% block content %}
<header class="bg-primary text-white">
    <div class="container text-center">
    <h1>Leaderboard</h1>
    <p class="lead">The best freighter pilots in the alliance</p>
    </div>
</header>


<section>
    <div class="container">
        <h2>Most contracts completed</h2>

        <ol>
            {% for c in ranking_completed %}
            <li>{{ c.name }} ({{ c.contracts_completed }} contracts)</li>
            {% endfor %}
        </ol>
    </div>
</section>

<section class="bg-light">
    <div class="container">
        <h2>Most volume moved</h2>

        <ol>
            {% for c in ranking_volume %}
            <li>{{ c.name }} ({{ c.volume_moved|intword }} m&sup3;)</li>
            {% endfor %}
        </ol>
    </div>
</section>

{% comment %} <section>
    <div class="container">
        <h2>Lowest average completion time</h2>

        <ol>
            {% for c in ranking_ttc %}
            <li>{{ c.name }} ({{ c.average_ttc }})</li>
            {% endfor %}
        </ol>
    </div>
</section> {% endcomment %}
{% endblock %}